export const HANGMAN_WORDS = [
  "act", "add", "age", "air", "ant", "ape", "arc", "arm", "art", "ash",
  "ask", "bag", "bar", "bat", "bay", "bed", "bee", "bet", "big", "bin",
  "bit", "bow", "box", "boy", "bug", "bus", "but", "buy", "cab", "can",
  "cap", "car", "cat", "cop", "cot", "cow", "cry", "cup", "cut", "dad",
  "dam", "day", "den", "dew", "did", "dig", "dim", "dog", "dot", "dry",
  "due", "dug", "ear", "eat", "egg", "elf", "elk", "elm", "end", "era",
  "eve", "eye", "fan", "far", "fat", "fax", "fed", "few", "fig", "fin",
  "fir", "fit", "fix", "fly", "fog", "for", "fox", "fry", "fun", "fur",
  "gap", "gas", "gem", "get", "gin", "god", "got", "gum", "gun", "gut",
  "guy", "gym", "had", "ham", "has", "hat", "hay", "hen", "her", "hid",
  "him", "hip", "his", "hit", "hog", "hop", "hot", "how", "hub", "hug",
  "hum", "hut", "ice", "icy", "ill", "ink", "inn", "ion", "irk", "its",
  "ivy", "jab", "jag", "jam", "jar", "jaw", "jay", "jet", "jig", "job",
  "jog", "joy", "jug", "jut", "keg", "ken", "key", "kid", "kin", "kit",
  "lab", "lad", "lag", "lap", "law", "lay", "lea", "led", "leg", "let",
  "lid", "lie", "lip", "lit", "log", "lot", "low", "lug", "mad", "man",
  "map", "mat", "maw", "max", "may", "men", "met", "mid", "mix", "mob",
  "mom", "mop", "mud", "mug", "nab", "nag", "nap", "net", "new", "nil",
  "nip", "nit", "nod", "nor", "not", "now", "nun", "nut", "oak", "oar",
  "oat", "odd", "off", "oft", "oil", "old", "one", "opt", "orb", "ore",
  "our", "out", "owe", "owl", "own", "pad", "pal", "pan", "pat", "paw",
  "pay", "pea", "peg", "pen", "pep", "per", "pet", "pie", "pig", "pin",
  "pit", "pod", "pop", "pot", "pry", "pub", "pug", "pun", "pup", "put",
  "rag", "ram", "ran", "rap", "rat", "raw", "ray", "red", "rib", "rid",
  "rig", "rim", "rip", "rob", "rod", "roe", "rot", "row", "rub", "rug",
  "rum", "run", "rut", "rye", "sad", "sag", "sap", "sat", "saw", "say",
  "sea", "set", "sew", "she", "shy", "sin", "sip", "sir", "sis", "sit",
  "six", "ski", "sky", "sly", "sob", "sod", "son", "sop", "sot", "sow",
  "soy", "spa", "spy", "sty", "sub", "sue", "sum", "sun", "sup", "tab",
  "tad", "tag", "tan", "tap", "tar", "tax", "tea", "ten", "the", "thy",
  "tic", "tie", "tin", "tip", "toe", "ton", "too", "top", "tot", "tow",
  "toy", "try", "tub", "tug", "two", "urn", "use", "van", "vat", "vet",
  "via", "vie", "vow", "wad", "wag", "war", "was", "wax", "way", "web",
  "wed", "wet", "who", "why", "wig", "win", "wit", "woe", "wok", "won",
  "woo", "wow", "yak", "yam", "yap", "yaw", "yea", "yes", "yet", "yew",
  "you", "zap", "zen", "zip", "zoo",
  "able", "also", "area", "army", "away", "back", "ball", "band", "bank", "base",
  "bath", "bear", "beat", "been", "bell", "belt", "best", "bird", "blow", "blue",
  "boat", "body", "bold", "bone", "book", "boot", "born", "both", "bowl", "burn",
  "busy", "cake", "call", "calm", "came", "camp", "card", "care", "case", "cash",
  "cast", "cave", "cell", "chat", "chef", "city", "clay", "clip", "club", "coal",
  "coat", "code", "coin", "cold", "come", "cook", "cool", "copy", "cord", "core",
  "corn", "cost", "crew", "crop", "cure", "curl", "cute", "dare", "dark", "data",
  "date", "dawn", "deal", "dear", "deck", "deed", "deep", "desk", "dial", "diet",
  "dirt", "disc", "dish", "dock", "door", "down", "draw", "drop", "drum", "dual",
  "duck", "dull", "dusk", "dust", "duty", "each", "earn", "ease", "east", "easy",
  "edge", "else", "even", "ever", "evil", "exam", "exit", "face", "fact", "fair",
  "fall", "fame", "farm", "fast", "fear", "feed", "feel", "feet", "fell", "felt",
  "file", "fill", "film", "find", "fine", "fire", "firm", "fish", "five", "flag",
  "flat", "flew", "flow", "fold", "folk", "food", "fool", "foot", "ford", "fork",
  "form", "fort", "four", "free", "frog", "from", "fuel", "full", "fund", "gain",
  "game", "gang", "gate", "gave", "gear", "gift", "girl", "give", "glad", "glow",
  "goal", "goat", "gold", "golf", "gone", "good", "grab", "gray", "grew", "grow",
  "gulf", "hair", "half", "hall", "hand", "hang", "hard", "harm", "hate", "have",
  "head", "hear", "heat", "held", "help", "herb", "hero", "hide", "high", "hill",
  "hint", "hire", "hold", "hole", "holy", "home", "hood", "hook", "hope", "horn",
  "host", "hour", "huge", "hunt", "hurt", "idea", "inch", "into", "iron", "item",
  "jack", "jazz", "join", "joke", "jump", "jury", "just", "keen", "keep", "kick",
  "kill", "kind", "king", "kiss", "kite", "knee", "knew", "knit", "know", "lace",
  "lack", "lady", "lake", "lamb", "lamp", "land", "lane", "last", "late", "lawn",
  "lead", "leaf", "lean", "left", "lend", "lens", "less", "life", "lift", "like",
  "lime", "line", "link", "lion", "list", "live", "load", "loan", "lock", "logo",
  "lone", "long", "look", "loop", "lord", "lose", "loss", "lost", "loud", "love",
  "luck", "lump", "lung", "made", "mail", "main", "make", "male", "mall", "many",
  "mark", "mask", "mass", "mate", "math", "meal", "mean", "meat", "meet", "melt",
  "memo", "menu", "mere", "mesh", "mile", "milk", "mill", "mind", "mine", "mint",
  "miss", "mist", "mode", "mold", "mood", "moon", "more", "most", "move", "much",
  "must", "nail", "name", "navy", "near", "neat", "neck", "need", "nest", "news",
  "next", "nice", "nine", "node", "none", "noon", "norm", "nose", "note", "noun",
  "okay", "once", "only", "onto", "open", "oral", "over", "pace", "pack", "page",
  "paid", "pain", "pair", "pale", "palm", "park", "part", "pass", "past", "path",
  "peak", "pear", "pick", "pile", "pine", "pink", "pipe", "plan", "play", "plot",
  "plug", "plus", "poem", "pole", "poll", "pond", "pool", "poor", "port", "post",
  "pour", "pray", "pull", "pump", "pure", "push", "race", "rack", "rail", "rain",
  "rank", "rare", "rate", "read", "real", "rear", "reed", "rely", "rent", "rest",
  "rice", "rich", "ride", "ring", "ripe", "rise", "risk", "road", "roar", "robe",
  "rock", "role", "roll", "roof", "room", "root", "rope", "rose", "rule", "rush",
  "rust", "safe", "sail", "sake", "sale", "salt", "same", "sand", "save", "seal",
  "seat", "seed", "seek", "seem", "seen", "self", "sell", "send", "sent", "ship",
  "shop", "shot", "show", "shut", "sick", "side", "sign", "silk", "sing", "sink",
  "site", "size", "skin", "skip", "slip", "slow", "snow", "soap", "soft", "soil",
  "sold", "sole", "some", "song", "soon", "sort", "soul", "soup", "sour", "spot",
  "star", "stay", "stem", "step", "stir", "stop", "such", "suit", "sure", "swim",
  "tail", "take", "tale", "talk", "tall", "tank", "tape", "task", "team", "tear",
  "tell", "tend", "tent", "term", "test", "text", "than", "that", "them", "then",
  "they", "thin", "this", "thus", "tide", "tidy", "tile", "till", "time", "tiny",
  "tire", "told", "toll", "tone", "took", "tool", "tour", "town", "tree", "trip",
  "true", "tube", "tune", "turn", "twin", "type", "unit", "upon", "used", "user",
  "vain", "vary", "vast", "veil", "vein", "very", "view", "vine", "vote", "wage",
  "wait", "wake", "walk", "wall", "want", "ward", "warm", "warn", "wash", "wave",
  "weak", "wear", "weed", "week", "well", "went", "were", "west", "what", "when",
  "whip", "wide", "wife", "wild", "will", "wind", "wine", "wing", "wipe", "wire",
  "wise", "wish", "with", "wolf", "wood", "wool", "word", "work", "worm", "worn",
  "wrap", "yard", "year", "yell", "your", "zero", "zone",
  "apple", "arrow", "beach", "brain", "bread", "brick", "brush", "cabin", "camel",
  "candy", "chair", "charm", "chess", "chest", "chief", "child", "chill", "chord",
  "civic", "claim", "class", "clerk", "cliff", "clock", "cloud", "coach", "coast",
  "coral", "couch", "crane", "crash", "cream", "creek", "crime", "crisp", "crown",
  "curve", "dance", "draft", "drain", "dream", "dress", "drift", "drink", "drive",
  "eagle", "earth", "elbow", "empty", "enemy", "enjoy", "entry", "equal", "event",
  "exact", "extra", "fable", "fairy", "faith", "fancy", "feast", "fence", "ferry",
  "field", "flame", "flash", "fleet", "flesh", "float", "flood", "floor", "flour",
  "flute", "focus", "force", "forge", "frame", "fresh", "front", "frost", "fruit",
  "ghost", "giant", "glass", "globe", "glove", "grace", "grade", "grain", "grand",
  "grant", "grape", "grass", "grave", "great", "green", "greet", "grill", "grove",
  "guard", "guess", "guest", "guide", "guild", "habit", "happy", "harsh", "heart",
  "heavy", "hello", "honey", "horse", "hotel", "house", "human", "humor", "ideal", "image",
  "index", "inner", "input", "issue", "ivory", "jewel", "joint", "judge", "juice",
  "knife", "knock", "label", "labor", "lance", "large", "laser", "later", "laugh",
  "layer", "learn", "lease", "lemon", "level", "light", "limit", "linen", "liver",
  "local", "logic", "loyal", "lunch", "magic", "major", "maple", "march", "match",
  "mayor", "medal", "melon", "mercy", "merit", "metal", "meter", "might", "minor",
  "minus", "mixed", "model", "money", "month", "moral", "motor", "mount", "mouse",
  "mouth", "movie", "music", "naked", "nerve", "never", "night", "noble", "noise",
  "north", "noted", "novel", "nurse", "ocean", "offer", "olive", "onion", "opera",
  "orbit", "order", "organ", "other", "outer", "owner", "paint", "panel", "paper",
  "party", "pasta", "patch", "pause", "peace", "peach", "pearl", "pedal", "penny",
  "phase", "phone", "photo", "piano", "piece", "pilot", "pitch", "pizza", "place",
  "plain", "plane", "plant", "plate", "plaza", "plead", "pluck", "point", "poker",
  "polar", "porch", "pound", "power", "press", "price", "pride", "prime", "print",
  "prior", "prize", "proof", "proud", "prove", "pulse", "punch", "pupil", "queen",
  "quest", "quick", "quiet", "quilt", "quite", "quote", "radar", "radio", "raise",
  "rally", "ranch", "range", "rapid", "ratio", "reach", "react", "ready", "realm",
  "rebel", "refer", "reign", "relax", "relay", "renew", "repay", "reply", "reset",
  "rider", "ridge", "rifle", "right", "rigid", "rival", "river", "roast", "robin",
  "robot", "rocky", "roman", "rough", "round", "route", "rover", "royal", "rugby",
  "ruler", "rural", "saint", "salad", "salon", "sandy", "satin", "sauce", "scale",
  "scare", "scarf", "scene", "scent", "scope", "score", "scout", "scrap", "sense",
  "serve", "seven", "shade", "shake", "shall", "shame", "shape", "share", "sharp",
  "sheep", "sheet", "shelf", "shell", "shift", "shine", "shirt", "shock", "shoot",
  "shore", "short", "shout", "sight", "silly", "since", "siren", "skill", "skirt",
  "skull", "slate", "slave", "sleep", "slice", "slide", "slope", "small", "smart",
  "smell", "smile", "smoke", "snake", "solar", "solid", "solve", "sorry", "sound",
  "south", "space", "spare", "spark", "speak", "speed", "spell", "spend", "spice",
  "spine", "spite", "split", "spoke", "sport", "spray", "squad", "stack", "staff",
  "stage", "stain", "stair", "stake", "stall", "stamp", "stand", "stark", "start",
  "state", "steak", "steal", "steam", "steel", "steep", "steer", "stick", "still",
  "stock", "stone", "stool", "store", "storm", "story", "stove", "strap", "straw",
  "strip", "stuck", "study", "stuff", "style", "sugar", "suite", "sunny", "super",
  "surge", "sweet", "swift", "swing", "sword", "table", "taste", "teach", "teeth",
  "tempo", "thank", "theft", "theme", "thick", "thief", "thing", "think", "third",
  "thorn", "those", "three", "threw", "throw", "thumb", "tiger", "tight", "timer",
  "tired", "title", "toast", "today", "token", "tooth", "topic", "torch", "total",
  "touch", "tough", "towel", "tower", "toxic", "trace", "track", "trade", "trail",
  "train", "trait", "trash", "treat", "trend", "trial", "tribe", "trick", "tried",
  "troop", "truck", "truly", "trunk", "trust", "truth", "tulip", "tumor", "tuner",
  "twice", "twist", "uncle", "under", "unite", "unity", "until", "upper", "upset",
  "urban", "usage", "usual", "valid", "value", "vault", "venue", "verse", "video",
  "vigor", "villa", "vinyl", "viola", "viral", "virus", "visit", "vital", "vivid",
  "vocal", "voice", "voter", "waste", "watch", "water", "weave", "wheat", "wheel",
  "where", "which", "while", "white", "whole", "whose", "woman", "world", "worry",
  "worse", "worst", "worth", "would", "wound", "wrist", "write", "wrong", "yacht",
  "yield", "young", "youth", "zebra",
] as const;

export const DICTIONARY = new Set<string>(HANGMAN_WORDS);
